In [2]:
import torch
print(torch.backends.mps.is_available())

True


In [7]:
tensor0d=torch.tensor(1)
print(tensor0d)
print(tensor0d.dtype)

tensor(1)
torch.int64


In [8]:
tensorfloat=torch.tensor(1.0)
print(tensorfloat)
print(tensorfloat.dtype)

tensor(1.)
torch.float32


In [10]:
convert=tensor0d.to(torch.float32)
print(convert)
print(convert.dtype)

tensor(1.)
torch.float32


In [12]:
tensor2d=torch.tensor([[1,2,5],[3,4,6]])
print(tensor2d)
print(tensor2d.dtype)

tensor([[1, 2, 5],
        [3, 4, 6]])
torch.int64


In [13]:
tensor2d.shape

torch.Size([2, 3])

In [14]:
tensor2d.reshape(3,2)
print(tensor2d.reshape(3,2))

tensor([[1, 2],
        [5, 3],
        [4, 6]])


In [17]:
tensor2d.view(3,2)

tensor([[1, 2],
        [5, 3],
        [4, 6]])

In [26]:
tensor2d=tensor2d.T
print(tensor2d)

tensor([[1, 2, 5],
        [3, 4, 6]])


In [27]:
tensor2d.T

tensor([[1, 3],
        [2, 4],
        [5, 6]])

In [28]:
tensor2d.matmul(tensor2d.T)

tensor([[30, 41],
        [41, 61]])

In [29]:
tensor2d @ tensor2d.T

tensor([[30, 41],
        [41, 61]])

In [32]:
import torch.nn.functional as F
y=torch.tensor([1.0]) #true label
x1=torch.tensor([1.1])
w1=torch.tensor([2.2])
b=torch.tensor([0.0])
z=x1 * w1 + b
a=torch.sigmoid(z)
print(a)  # predicted label
loss=F.binary_cross_entropy(a, y)
print(loss)

tensor([0.9183])
tensor(0.0852)


In [34]:
import torch.nn.functional as F
from torch.autograd import grad
y=torch.tensor([1.0]) #true label
x1=torch.tensor([1.1])
w1=torch.tensor([2.2], requires_grad=True)
b=torch.tensor([0.0], requires_grad=True)
z=x1 * w1 + b
a=torch.sigmoid(z)
print(a)  # predicted label
loss=F.binary_cross_entropy(a, y)
print(loss)
grad_L_w1=grad(loss, w1, retain_graph=True)
print(grad_L_w1)
grad_L_b=grad(loss, b, retain_graph=True)
print(grad_L_b)

tensor([0.9183], grad_fn=<SigmoidBackward0>)
tensor(0.0852, grad_fn=<BinaryCrossEntropyBackward0>)
(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [35]:
loss.backward()
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


In [36]:
import torch
class NeuralNetwork(torch.nn.Module):
    def __init__(self,num_inputs,num_outputs):
        super().__init__()
        self.layers=torch.nn.Sequential(
            # First layer
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),
            # Second layer
            torch.nn.Linear(30,20),
            torch.nn.ReLU(),
            # Output layer
            torch.nn.Linear(20, num_outputs)
        )

    def forward(self, x):
        logits= self.layers(x)
        return logits
model=NeuralNetwork(50,3)
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [ ]:
num_params=sum(p.numel() for p in model.parameters() if p.requires_grad)
print(num_params)

2213


In [41]:
print(model.layers[0].weight)
print(model.layers[0].weight.shape)

Parameter containing:
tensor([[-0.1386, -0.0677, -0.0350,  ...,  0.1147, -0.0802, -0.0487],
        [-0.0259,  0.1189, -0.0658,  ...,  0.0611,  0.0699, -0.0820],
        [ 0.0079, -0.0471, -0.0505,  ...,  0.1064,  0.0451,  0.0961],
        ...,
        [-0.1150, -0.0778, -0.0254,  ...,  0.0140, -0.0597, -0.0407],
        [-0.0557,  0.1023,  0.1059,  ...,  0.0257, -0.1319, -0.1151],
        [ 0.1067, -0.1073,  0.0022,  ..., -0.0690, -0.0135,  0.0540]],
       requires_grad=True)
torch.Size([30, 50])


In [42]:
model.layers[0].bias

Parameter containing:
tensor([ 0.0107, -0.0554, -0.0962,  0.1317,  0.1019, -0.0870, -0.1150,  0.0146,
        -0.0281,  0.0488,  0.0971, -0.0843,  0.1381,  0.1333,  0.1053, -0.1336,
         0.1399,  0.0155,  0.0025,  0.0815, -0.0629,  0.1364,  0.1040, -0.1295,
         0.0960, -0.1206,  0.0667, -0.0857, -0.1409,  0.0378],
       requires_grad=True)

In [ ]:
#checking the feedforward pass
torch.manual_seed(45)
X=torch.rand(1,50)
out=model(X)
print(out)
print(out.shape)

tensor([[ 0.1361, -0.1858,  0.1672]], grad_fn=<AddmmBackward0>)
torch.Size([1, 3])


In [ ]:
#checking gradients
with torch.no_grad():
    out=model(X)
print(out)
print(out.shape)

tensor([[ 0.1361, -0.1858,  0.1672]])
torch.Size([1, 3])


In [ ]:
# Softmax for multi-class classification
with torch.no_grad():
    out=torch.softmax(out, dim=1)
print(out)

tensor([[0.3628, 0.2629, 0.3743]])


In [47]:
X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])

y_train = torch.tensor([0, 0, 0, 1, 1])
X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6],
])

y_test = torch.tensor([0, 1])

In [51]:
from torch.utils.data import Dataset
class mydataset(Dataset):
    def __init__(self, X, y):
        self.features = X
        self.labels = y

    def __len__(self):
        return self.labels.shape[0]

    def __getitem__(self, idx):
        one_x= self.features[idx]
        one_y= self.labels[idx]
        return one_x, one_y
train_ds=mydataset(X_train, y_train)
test_ds=mydataset(X_test, y_test)

In [52]:
len(train_ds)

5

In [54]:
from torch.utils.data import DataLoader
torch.manual_seed(45)
train_loader = DataLoader(train_ds, batch_size=2, shuffle=True,num_workers=0)
test_loader = DataLoader(test_ds, batch_size=2, shuffle=False, num_workers=0)

In [55]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx+1}:", x, y)

Batch 1: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])
Batch 2: tensor([[-1.2000,  3.1000],
        [ 2.7000, -1.5000]]) tensor([0, 1])
Batch 3: tensor([[-0.5000,  2.6000]]) tensor([0])


In [56]:
train_loader = DataLoader(train_ds, batch_size=2, shuffle=True, num_workers=0,drop_last=True)

In [57]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx+1}:", x, y)

Batch 1: tensor([[-0.5000,  2.6000],
        [ 2.3000, -1.1000]]) tensor([0, 1])
Batch 2: tensor([[-1.2000,  3.1000],
        [-0.9000,  2.9000]]) tensor([0, 0])


In [58]:
import torch.nn.functional as F


torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

num_epochs = 3

for epoch in range(num_epochs):

    model.train()
    for batch_idx, (features, labels) in enumerate(train_loader):

        logits = model(features)

        loss = F.cross_entropy(logits, labels) # Loss function

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        ### LOGGING
        print(f"Epoch: {epoch+1:03d}/{num_epochs:03d}"
              f" | Batch {batch_idx:03d}/{len(train_loader):03d}"
              f" | Train/Val Loss: {loss:.2f}")

    model.eval()

Epoch: 001/003 | Batch 000/002 | Train/Val Loss: 0.75
Epoch: 001/003 | Batch 001/002 | Train/Val Loss: 0.65
Epoch: 002/003 | Batch 000/002 | Train/Val Loss: 0.44
Epoch: 002/003 | Batch 001/002 | Train/Val Loss: 0.13
Epoch: 003/003 | Batch 000/002 | Train/Val Loss: 0.03
Epoch: 003/003 | Batch 001/002 | Train/Val Loss: 0.00


In [59]:
model.eval()
with torch.no_grad():
    outputs=model(X_train)
print(outputs)

tensor([[ 2.8569, -4.1618],
        [ 2.5382, -3.7548],
        [ 2.0944, -3.1820],
        [-1.4814,  1.4816],
        [-1.7176,  1.7342]])


In [61]:
torch.set_printoptions(precision=3, sci_mode=False)
probas= torch.softmax(outputs, dim=1)
print(probas)

tensor([[    0.999,     0.001],
        [    0.998,     0.002],
        [    0.995,     0.005],
        [    0.049,     0.951],
        [    0.031,     0.969]])


In [62]:
predictions=torch.argmax(probas, dim=1)
print(predictions)

tensor([0, 0, 0, 1, 1])


In [63]:
predictions==y_train

tensor([True, True, True, True, True])

In [64]:
def compute_accuracy(model, dataloader):
    
    model = model.eval()
    correct = 0.0
    total_examples = 0

    for idx, (features, labels) in enumerate(dataloader):

        with torch.no_grad():
            logits = model(features)

        predictions = torch.argmax(logits, dim=1)
        compare = labels == predictions
        correct += torch.sum(compare)
        total_examples += len(compare)

    return (correct / total_examples).item()


In [65]:
compute_accuracy(model, train_loader), compute_accuracy(model, test_loader)

(1.0, 1.0)

In [67]:
torch.save(model.state_dict(), "model.pth")

In [71]:
model=NeuralNetwork(2,2)
model.load_state_dict(torch.load("model.pth",weights_only=True))

<All keys matched successfully>

In [72]:
torch.cuda.is_available()

False

In [77]:
tensor_1 = torch.tensor([1., 2., 3.])
tensor_2 = torch.tensor([4., 5., 6.])

print(tensor_1 + tensor_2)
tensor_1 = tensor_1.to("mps")
tensor_2 = tensor_2.to("mps")

print(tensor_1 + tensor_2)

tensor([5., 7., 9.])
tensor([5., 7., 9.], device='mps:0')


In [76]:
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
device

device(type='mps')

In [78]:
torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)

# New: Define a device variable that defaults to a GPU.
device = torch.device("mps")
# New: Transfer the model onto the GPU.
model.to(device)

optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

num_epochs = 3

for epoch in range(num_epochs):

    model.train()
    for batch_idx, (features, labels) in enumerate(train_loader):

        # New: Transfer the data onto the GPU.
        features, labels = features.to(device), labels.to(device)    #C
        logits = model(features)
        loss = F.cross_entropy(logits, labels) # Loss function

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        ### LOGGING
        print(f"Epoch: {epoch+1:03d}/{num_epochs:03d}"
              f" | Batch {batch_idx:03d}/{len(train_loader):03d}"
              f" | Train/Val Loss: {loss:.2f}")

    model.eval()

Epoch: 001/003 | Batch 000/002 | Train/Val Loss: 0.75
Epoch: 001/003 | Batch 001/002 | Train/Val Loss: 0.65
Epoch: 002/003 | Batch 000/002 | Train/Val Loss: 0.44
Epoch: 002/003 | Batch 001/002 | Train/Val Loss: 0.13
Epoch: 003/003 | Batch 000/002 | Train/Val Loss: 0.03
Epoch: 003/003 | Batch 001/002 | Train/Val Loss: 0.00
